version: "3" 
services:
  web_enocis:
    image: alexrogna/enocis_web:prod
    expose:
      - 3000
    volumes:
      - ./enocis/storage:/opt/app/storage
    env_file:
      - .env/production/database_enocis
      - .env/production/web_enocis
    environment:
      - VIRTUAL_HOST=enocis.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=enocis.alexrogna.com
      - DELAYED_JOB_HOST=delayed_job_enocis
    networks:
      - proxy
    restart: always
  delayed_job_enocis:
    image: alexrogna/enocis_web:prod
    command: ./bin/rails jobs:work
    env_file:
      - .env/production/database_enocis
      - .env/production/web_enocis
    environment:
      - DELAYED_JOB_HOST=0.0.0.0
    networks:
      - proxy
    restart: always
  database_enocis:
    image: postgres:13
    env_file:
      - .env/production/database_enocis
    volumes:
      - db_data_enocis:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_enocis:
    image: alexrogna/enocis_web:prod
    command: ["./wait-for", "--timeout=300", "database_enocis:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_enocis
      - .env/production/web_enocis
volumes:
  db_data_enocis:
networks:
  proxy: 