version: "3" 
services:
  web_enocis:
    image: alexrogna/enocis_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_enocis
      - .env/production/web_enocis
    environment:
      - VIRTUAL_HOST=enocis.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=enocis.alexrogna.com
    networks:
      - proxy
    restart: always

  database_enocis:
    image: postgres
    env_file:
      - .env/production/database_enocis
    volumes:
      - db_data_enocis:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_enocis:
    image: alexrogna/enocis_web:prod
    command: ["./wait-for", "--timeout=300", "database_enocis:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_enocis
      - .env/production/web_enocis
volumes:
  db_data_enocis:
networks:
  proxy: